language: php

php:
  - "hhvm"
  - "7.1"
  - "7.0"

install:
    - "composer install --ignore-platform-reqs"

before_script:
    - "mkdir -p ./build/logs"

script:
    - "./robo test"

after_success:
    - "php ./vendor/bin/coveralls -v"